### ISSUE TITLE
Launch mods using the openra-* wrapper scripts

### ISSUE THREAD

**Issue by pchote** [diddledan/openra-snap#5]
The current launch commands call `OpenRA.Game.exe` directly rather than the `openra-<mod>` launchers.  This isn't ideal, as users miss out on the crash info dialog if something goes wrong.

The `openra` launcher ([snapcraft.yaml#L19](https://github.com/diddledan/openra-snap/blob/master/snap/snapcraft.yaml#L19)) also will not work for release-20171014 and later, and will immediately crash with an error like #4.

Great job packaging OpenRA, btw!

**Comment by diddledan** [comment]
The launchers now call the upstream commands to launch the games (i.e. the `openra-$mod` scripts)
